# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playlist.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eplaylist.proto\x12\x08playlist\x1a\x1bgoogle/protobuf/empty.proto\"3\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"]\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1c\n\x04user\x18\x03 \x01(\x0b\x32\x0e.playlist.User\x12\x19\n\x11total_songs_count\x18\x04 \x01(\x03\"\x15\n\x13PlaylistListRequest\"%\n\x17PlaylistRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xb9\x02\n\x12PlaylistController\x12=\n\x04List\x12\x1d.playlist.PlaylistListRequest\x1a\x12.playlist.Playlist\"\x00\x30\x01\x12\x32\n\x06\x43reate\x12\x12.playlist.Playlist\x1a\x12.playlist.Playlist\"\x00\x12\x43\n\x08Retrieve\x12!.playlist.PlaylistRetrieveRequest\x1a\x12.playlist.Playlist\"\x00\x12\x32\n\x06Update\x12\x12.playlist.Playlist\x1a\x12.playlist.Playlist\"\x00\x12\x37\n\x07\x44\x65stroy\x12\x12.playlist.Playlist\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'playlist_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=57
  _USER._serialized_end=108
  _PLAYLIST._serialized_start=110
  _PLAYLIST._serialized_end=203
  _PLAYLISTLISTREQUEST._serialized_start=205
  _PLAYLISTLISTREQUEST._serialized_end=226
  _PLAYLISTRETRIEVEREQUEST._serialized_start=228
  _PLAYLISTRETRIEVEREQUEST._serialized_end=265
  _PLAYLISTCONTROLLER._serialized_start=268
  _PLAYLISTCONTROLLER._serialized_end=581
# @@protoc_insertion_point(module_scope)
